# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sara Mannseichner
email: saramannseichner@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi! My name is Sara Mannseichner and I'm a full stack web developper.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  saramannseichner

# Build settings
markdown: kramdown


gems:
  - jekyll-paginate
  - jekyll-compose

paginate: 6
paginate_path: "blog/page:num"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site
